s = input('Введите строку: ')
print(s[2])
print(s[-2])
print(s[0:5])
print(s[0:-2])
print(s[::2])
print(s[1::2])
print(s[::-1])
print(s[::-2]) # Строка в обратном порядке с выводом через 1 символ
print(len(s))